config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homepage#index'

  resources :homepage, only: [:index]

  resources :songs do
    resources :sounds, only: [:new, :create, :destroy]
    resources :texts, only: [:new, :create, :destroy]
    resources :arts, only: [:new, :create, :destroy]
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  mount_uploader :imgfile, ArtUploader

  belongs_to :song

  validates :imgfile, presence: { message: 'Must choose a file to upload' }
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  has_many :sounds, dependent: :destroy
  has_many :texts, dependent: :destroy
  has_many :arts, dependent: :destroy

  validates :title, presence: true
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  belongs_to :song

  validates :track_url, format: { with: URI.regexp }, if: 'track_url.present?'
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :song

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  #mount_uploader :avatar, AvatarUploader

  has_many :songs, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :username, presence: true, uniqueness: true

  def can_modify?(item)
    id == item.user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    keys = [
      { roles: [] },
      :username,
      :email,
      :current_password,
      :password,
      :password_confirmation,
    ]

    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(keys)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(keys)
    end
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :authenticate_user!

  def new
    @art = Art.new
    @song = Song.find(params[:song_id])
  end

  def create
    @song = Song.find(params[:song_id])

    begin
      @art = Art.new(art_params)
    rescue ActionController::ParameterMissing
      flash[:alert] = 'Must choose a file to upload'
      @art = Art.new
      @song = Song.find(params[:song_id])
      render('arts/new') && return
    end

    @art.song_id = params['song_id']


    if @art.save
      flash[:success] = 'Art saved successfully'
      redirect_to song_path(params['song_id'])
    else
      flash[:alert] = 'Problems saving Art'
      render 'arts/new'
    end
  end

  def art_params
    params.require(:art).permit(:imgfile)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_songs = Song.where(user_id: current_user.id).find_each
  end

  def show
    @song = Song.find(params[:id])
    @sounds = Sound.where(song_id: @song.id).find_each
    @texts = Text.where(song_id: @song.id).find_each
    @arts = Art.where(song_id: @song.id).find_each
  end

  def new
    @new_song = Song.new
  end

  def create
    @new_song = Song.new(song_params)
    @new_song.user_id = current_user.id
    if @new_song.save
      flash[:success] = 'Song saved successfully'
      redirect_to song_path(@new_song)
    else
      flash[:alert] = 'Problems saving song'
      @errors = @new_song.errors.full_messages
      render 'songs/new'
    end
  end

  def edit
    @new_song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title,
                                  :body)
  end
end

app/controllers/sounds_controller.rb
require 'soundcloud'

class SoundsController < ApplicationController
  before_action :authenticate_user!

  def new
    @sound = Sound.new
    @song = Song.find(params[:song_id])
  end

  def create
    client = Soundcloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
    @sound = Sound.new(sound_params)
    @song = Song.find(params[:song_id])
    track_url = @sound.track_url

    begin
      embed_info = client.get('/oembed', url: track_url)
      @sound.embed_info = embed_info['html']
    rescue SoundCloud::ResponseError
      flash[:alert] = 'Problems saving sound'
      render('sounds/new') && return
    end

    @sound.song_id = params['song_id']

    if @sound.save
      flash[:success] = 'Sound saved successfully'
      redirect_to song_path(params['song_id'])
    else
      flash[:alert] = 'Problems saving sound'
      @errors = @sound.errors.full_messages
      render 'sounds/new'
    end
  end


  def sound_params
    params.require(:sound).permit(:track_url, :embed_info)
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :authenticate_user!

  def new
    @text = Text.new
    @song = Song.find(params[:song_id])
  end

  def create
    @text = Text.new(text_params)
    @text.song_id = params['song_id']
    @song = Song.find(params[:song_id])

    if @text.save
      flash[:success] = 'Quote saved successfully'
      redirect_to song_path(params['song_id'])
    else
      flash[:alert] = 'Problems saving quote'
      @errors = @text.errors.full_messages
      render 'texts/new'
    end
  end

  def text_params
    params.require(:text).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if @errors  %>
  <% @errors.each do |message| %>
    <div data-alert class="alert-box alert round">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
 <% end %>
<% end %>

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <% type = 'success' if type == 'notice' %>
  <div class="callout <%= type %>" data-closable>
    <%= message %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/arts/_art.html.erb
<%= image_tag art.imgfile %>

app/views/arts/new.html.erb
<%= render 'application/errors' %>
<h2>New Art</h2>
<%= form_for [@song, @art] do |f| %>
  <%= f.file_field :imgfile %>

  <%= f.submit 'Save Art', class: 'button' %>
<% end %>

app/views/homepage/index.html.erb
<div class='row'>
  <div class='splash columns small-12 medium-8 medium-centered'>
    <h1>Songwriter</h2>
    <p>Your lyrics notebook on the web.</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Songwriter" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
    <script src="https://use.fontawesome.com/8bfb425632.js"></script>
  </head>
  <body>
    <nav class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li>
            <%= link_to 'Songwriter', root_path %>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Your Songs', songs_path %>
            </li>
            <li>
              <%= link_to "#{current_user.username}", edit_user_registration_path(@user)%>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, class: 'button', method: 'delete' %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path, class: 'button', method: 'get' %>
            </li>
            <li>
              <%= link_to 'Sign In', new_user_session_path, class: 'button', method: 'get' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= render "application/flash" %>
    <%= render "application/errors" %>

    <div class="row">
      <div class="columns content">
        <%= yield %>
      </div>
    </div>

    <% if Rails.env.test? %>
      <%= hidden_field_tag :testing, true  %>
    <% end %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= render 'application/errors' %>
<%= form_for @new_song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit 'Save Song', class: 'button' %>
<% end %>

app/views/songs/_media.html.erb
<div class='row quotes'>
  <% @texts.each do |text| %>
    <div class='large-4 columns quote'>
      <%= render partial: '/texts/text', object: text %>
    </div>
  <% end %>
</div>

<div class='row sounds'>
  <% @sounds.each do |sound| %>
    <div class='large-4 columns'>
      <%= render partial: './sounds/sound', object: sound  %>
    </div>
  <% end %>
</div>

<div class='row arts'>
  <% @arts.each do |art| %>
    <div class='large-4 columns'>
      <%= render partial: './arts/art', object: art %>
    </div>
  <% end %>
</div>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<div class="row">
  <div class="columns small-12">
    <%= render 'songs/form' %>
  </div>
</div>

app/views/songs/index.html.erb
<div class='song-index'>
  <h2>Your Songs</h2>
  <ul>
    <% @user_songs.each do |song| %>
      <li class='song-title'><%= link_to song.title, song_path(song) %></li>
    <% end %>
  </ul>

  <%= link_to 'Add New Song', new_song_path, class: "button" %>
</div>

app/views/songs/new.html.erb
<h2>New Song</h2>

<%= render 'songs/form' %>

app/views/songs/show.html.erb
<div class='row song-info'>
  <div class='large-6 columns'>
    <h3 class='song-title'><%= @song.title %></h3>
    <p><%= @song.body %></p>
  </div>
  <div class='large-6 columns song-controls'>
    <div class='button-group'>
      <%= link_to 'Edit Song', edit_song_path(@song.id), class: 'button' %>
      <%= link_to 'Add Sound', new_song_sound_path(@song.id), class: 'button' %>
      <%= link_to 'Add Quote', new_song_text_path(@song.id), class: 'button' %>
      <%= link_to 'Add Art', new_song_art_path(@song.id), class: 'button' %>
    </div>
  </div>
</div>
<hr>
<%= render '/songs/media' %>

app/views/sounds/_sound.html.erb
<%= sound.embed_info.html_safe %>

app/views/sounds/new.html.erb
<h2>Add Sound</h2>

<%= render 'application/errors' %>
<%= form_for [@song, @sound] do |f| %>

  <%= f.label :track_url, 'SoundCloud URL' %>
  <%= f.url_field :track_url %>

  <%= f.submit 'Save Sound', class: 'button' %>
<% end %>

app/views/texts/_text.html.erb
<i class="fa fa-quote-left" aria-hidden="true"></i>
<%= text.body %>
<i class="fa fa-quote-right" aria-hidden="true"></i>

app/views/texts/new.html.erb
<h2>Add Quote</h2>

<%= render 'application/errors' %>
<%= form_for [@song, @text] do |f| %>

  <%= f.label :body, 'Quote Body' %>
  <%= f.text_field :body %>

  <%= f.submit 'Save Quote', class: 'button' %>
<% end %>